services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo/create-custom-user.js:/docker-entrypoint-initdb.d/create-custom-user.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/

  js-server:
    build:
      context: ./js
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      MONGO_URI: mongodb://adrian:password@mongodb:27017/demo-database
